server: 
  port: 8089
 
spring: 
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RajeshShinde12/Indiazone
          search-paths: 
          - "config-store/*service"
